# Generated by Django 5.1.3 on 2024-11-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KotlinApp', '0003_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='name',
        ),
    ]
