# Generated by Django 5.1.3 on 2024-11-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KotlinApp', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='department',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
