# Generated by Django 5.1.3 on 2024-11-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KotlinApp', '0007_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
